CREATE TABLE IF NOT EXISTS user (
    user_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(70) NOT NULL,
    login varchar(50),
    name varchar(50),
    birthday date
);

CREATE TABLE IF NOT EXISTS film (
    film_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    genre_id int REFERENCES user (genre_id),
    mpa_rate varchar(5) REFERENCES mpa_values (name),
    name varchar(50),
    description varchar(500),
    release_date date,
    duration int
);

CREATE TABLE IF NOT EXISTS friendship(
    user_id int NOT NULL,
    friend_id int NOT NULL,
    status varchar(15),
    CONSTRAINT fk_friendship_user_id FOREIGN KEY (user_id) REFERENCES user (user_id),
    CONSTRAINT fk_friendship_friend_id FOREIGN KEY (friend_id) REFERENCES user (user_id),
    PRIMARY KEY (user_id, friend_id)
);

CREATE TABLE IF NOT EXISTS like(
    film_id int NOT NULL,
    user_id int NOT NULL,
    CONSTRAINT fk_like_film_id FOREIGN KEY (film_id) REFERENCES film (film_id),
    CONSTRAINT fk_like_user_id FOREIGN KEY (user_id) REFERENCES user (user_id),
    PRIMARY KEY (film_id, user_id)
);

CREATE TABLE IF NOT EXISTS genre(
    genre_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50)
);

CREATE TABLE IF NOT EXISTS mpa_values(
    mpa_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50)
);
